spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:8101/${POSTGRES_DB}
    #added a JDBC connection to the PostgreSQL database
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}